 *: {
  grid-columns: 1;
  grid-gap: 10;
 }

standard {
 attributes {
  grid-rows: 2;
  grid-gap: 10;
  model; metric;
  vendor; license; url; notes;
 };
 profiles {
  grid-rows: 2;
  grid-gap: 10;
  name {
   views {
    kinds {
     sources {
      path;
      window;
     }
    }
   }
  }
 }
 sources;
 datasets;
 attachments;
}